// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kazdscyirvhqicixjkqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthemRzY3lpcnZocWljaXhqa3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMTMyMDcsImV4cCI6MjA3NDY4OTIwN30.hgvpvZpqv1E5Bl_DvzdYlWZxI2i-WqlM846IaHBmLbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});